Increment added
capre-diem/calculator_DM pull request #25
Opened 2023-10-27 21:02 UTC by SaveliyKrivov

2023-10-27 21:20 UTC, DoAlvaro requested changes

2023-10-27 21:20 UTC, DoAlvaro commented on computing/natural/Natural.py
> +        return increment(self)
код не должен ничего returnить

2023-10-27 21:20 UTC, DoAlvaro commented on computing/natural/Natural.py
> +    def increment(self) -> Natural:
-> None

2023-10-28 16:46 UTC, DoAlvaro approved these changes

2023-10-28 16:46 UTC, merged

2023-10-28 16:49 UTC, TeUm3048 commented on computing/natural/increment.py
Как по мне читерно использовать 10 в массиве чисел, но даже на ASSемблере или C/C++ мы бы использовали переполнение. Там нам зато не надо было бы устанавливать значение в 0.

Можно мержить

А уже...