add
capre-diem/calculator_DM pull request #31
Opened 2023-10-28 19:17 UTC by dariaomnom

2023-10-28 19:29 UTC, TeUm3048 commented
Natural лежит заглушка раскоменченая.
Поменяй на свои фукцию и проверь ещё раз тесты

2023-10-28 19:36 UTC, TeUm3048 commented
У меня ничего не работает 
```python
        for i in range(len(increased)):
>           increased.data[i] += num2.data[i]
E           IndexError: list index out of range
```

2023-10-28 19:42 UTC, TeUm3048 requested changes

2023-10-28 19:42 UTC, TeUm3048 commented on computing/natural/add.py
>  from compare import compare
Не нужный импорт

2023-10-28 19:42 UTC, TeUm3048 commented on computing/natural/add.py
> +        increased.data[i] += num2.data[i]
```python
        for i in range(len(increased)):
>           increased.data[i] += num2.data[i]
E           IndexError: list index out of range
```

2023-10-28 20:02 UTC, dariaomnom commented
>> Natural лежит заглушка раскоменченая.
>> Поменяй на свои фукцию и проверь ещё раз тесты

не понял вообще, что нужно сделать(

2023-10-28 20:04 UTC, dariaomnom commented
а, типо вот это заменить на мою return Natural(str(int(self)+int(other))), понял

2023-10-31 12:59 UTC, TeUm3048 commented
@DoAlvaro так мы будем это мержить или как? Тебе тут что-то не нравилось вроде

2023-10-31 20:41 UTC, TeUm3048 approved these changes

2023-11-01 00:38 UTC, merged