get_degree: done + tests
capre-diem/calculator_DM pull request #58
Opened 2023-11-03 22:27 UTC by Cuga77

2023-11-04 16:31 UTC, TeUm3048 requested changes
Функция правильная, есть небольшие ошибки в ините

2023-11-04 16:31 UTC, TeUm3048 commented on computing/polynom/Polynom.py
Если мы нигде больше, кроме инита не используем поле degree, его следует удалить из класса

2023-11-04 16:31 UTC, TeUm3048 commented on computing/polynom/Polynom.py
>          self.degree = len(value)
Соответственно это не надо

2023-11-04 16:31 UTC, TeUm3048 commented on tests/computing/polynom/get_degree_test.py
> +    assert p.get_degree() == -1
Хм, странная конструкция.
Многочлен, который не имеет ни одного коэффициента.
Кажется, он должен инициализироваться нулём.

2023-11-04 17:07 UTC, Cuga77 commented on tests/computing/polynom/get_degree_test.py
> +    assert p.get_degree() == -1
тут ты прав, я фиксану

> Хм, странная конструкция. Многочлен, который не имеет ни одного коэффициента. Кажется, он должен инициализироваться нулём.

2023-11-04 19:30 UTC, Cuga77 commented on tests/computing/polynom/get_degree_test.py
> +    assert p.get_degree() == -1
> Хм, странная конструкция. Многочлен, который не имеет ни одного коэффициента. Кажется, он должен инициализироваться нулём.

в итоге у меня не получилось. либо я что-то не понимаю и написал неверно

2023-11-05 10:56 UTC, TeUm3048 commented on tests/computing/polynom/get_degree_test.py
> +    assert p.get_degree() == -1
В ините нужно добавить проверку:
```python
    def __init__(self, value: list[Rational]) -> None:
        if value == []:
            self.data = [Rational("0")]
            return
        self.data = value
        while len(self.data) > 1 and self.data[-1] == Rational("0"):
            self.data.pop()
```

2023-11-05 12:32 UTC, TeUm3048 commented on computing/polynom/get_leading_coefficient.py
> +        return None
У многочлена теперь всегда есть не пустая data
Просто 
```python
return self.data[-1]
```

2023-11-05 12:32 UTC, TeUm3048 commented on computing/rational/Rational.py
> +
Стопе, а зачем тут поменялся код? и убран simplify?

2023-11-05 12:32 UTC, TeUm3048 commented on tests/computing/polynom/get_leading_coefficient_test.py
> +    assert p.get_leading_coefficient() is None
```python
    p = Polynom([])
    assert p.get_leading_coefficient() == Rational('0')
```

2023-11-05 13:29 UTC, TeUm3048 approved these changes

2023-11-05 13:32 UTC, merged