add function added
capre-diem/calculator_DM pull request #61
Opened 2023-11-03 23:32 UTC by SaveliyKrivov

2023-11-04 11:09 UTC, DoAlvaro requested changes

2023-11-04 11:09 UTC, DoAlvaro commented on computing/polynom/add.py
> +    num1 = self
copy()

2023-11-04 11:09 UTC, DoAlvaro commented on computing/polynom/add.py
> +    num2 = other
copy()

2023-11-04 11:09 UTC, DoAlvaro commented on computing/polynom/add.py
> +    res = Polynom([])
???

2023-11-04 11:09 UTC, DoAlvaro commented on computing/polynom/add.py
> +        num1.data.append(Rational("0"))
сделай без доп памяти

2023-11-05 11:51 UTC, TeUm3048 reviewed
ОК, жду тесты и мержим

2023-11-05 12:59 UTC, merged