GCF_Polynom
capre-diem/calculator_DM pull request #66
Opened 2023-11-04 18:57 UTC by IvanMavlikaev

2023-11-04 20:00 UTC, DoAlvaro requested changes

2023-11-04 20:00 UTC, DoAlvaro commented on computing/polynom/GCF.py
> +def DCF(self: Polynom, other: Polynom)-> Polynom:
dcf ??

2023-11-04 20:00 UTC, DoAlvaro commented on computing/polynom/GCF.py
> +    else:
убери элсе

2023-11-04 20:00 UTC, DoAlvaro commented on computing/polynom/Polynom.py
> +        return GCF(self, other)
напиши тесты

2023-11-04 20:04 UTC, IvanMavlikaev commented on computing/polynom/GCF.py
> +def DCF(self: Polynom, other: Polynom)-> Polynom:
могу NOD назвать

2023-11-05 18:09 UTC, DoAlvaro requested changes

2023-11-05 18:09 UTC, DoAlvaro commented on computing/polynom/gcd.py
> +
если pol1 и pol2 == 0 - zerodivisionerror

2023-11-05 19:13 UTC, TeUm3048 commented on computing/polynom/gcd.py
> +
Неправда
Если хотя бы один из полиномов равен 0 — gcd равен второму числу.
gcd(a, 0) = a
Если оба числа равны 0
gcd(0, 0) = 0

2023-11-06 12:54 UTC, DoAlvaro approved these changes

2023-11-06 12:54 UTC, merged